version: '2'

networks:
  app-tier:
    driver: bridge

services:
  memcached:
    image: 'bitnami/memcached:latest'
    command: /opt/bitnami/scripts/memcached/run.sh -vvv
    networks:
      - app-tier
    ports:
      - "11211:11211"